@startuml
title: Worttrainer Reloaded

class WortEintrag {
  -wort : String
  -bildUrl : String
  --
  +WortEintrag(String wort, String bildUrl)
  +void setWort(String wort)
  +boolean checkWort(String wort)
  +void setBildUrl(String bildUrl)
  +boolean checkBildUrl(String bildUrl)
  +String getWort()
  +String getBildUrl()
  +String toString()
  +boolean equals(Object obj)
}

class WortTrainer {
  -eintraege : List<WortEintrag>
  -auswahl : WortEintrag
  --
  +WortTrainer()
  +List<WortEintrag> getEintraege()
  +void setEintraege(List<WortEintrag> eintraege)
  +WortEintrag waehleZufaelligenEintrag()
  +WortEintrag waehleEintrag(int index)
  +void addEintrag(WortEintrag eintrag)
  +void removeEintrag(WortEintrag eintrag)
  +WortEintrag getAuswahl()
  +void setAuswahl(WortEintrag eintrag)
}

@enduml