name: Build and Release JAR

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Build JAR
        run: ./gradlew build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/libs/*.jar

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/libs/*.jar
          asset_name: app-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
